### ISSUE TITLE
Push to a branch failed with 403

### ISSUE THREAD

**Issue by qurname2** [cropalato/terraform-provider-etcd#1]
Hi, there!
I'd like to add some feature regarding SSL.
I've prepared a branch locally, but can't push it to your repo.
`remote: Permission to cropalato/terraform-provider-etcd.git denied to qurname2.
fatal: unable to access 'https://github.com/cropalato/terraform-provider-etcd.git/': The requested URL returned error: 403`
Could you please open your repo for creating branches and PR?

**Comment by cropalato** [comment]
Hi @qurname2,
Thanks for your contribution. The problem has been fixed and you should be able to create your PR.

Please let me know if you are still facing this problem.

**Comment by qurname2** [comment]
Hi, @cropalato, I still receive 403 =(

**Comment by cropalato** [comment]
Hi @qurname2,
I asked a friend of mine to test create a PR and it works for him.
I am not sure what is going on from your side, but I can see only a fork from this project. If you don't mind, Can you try fork the project, push your changes and create the PR from your forked project and mine? That is how I usually push my PRs to other projects.
